import {
  AtomIcon,
  BinaryIcon,
  BookIcon,
  BookOpenIcon,
  BrainIcon,
  BriefcaseIcon,
  CalculatorIcon,
  CameraIcon,
  CodeIcon,
  CoffeeIcon,
  DatabaseIcon,
  DnaIcon,
  DumbbellIcon,
  FilmIcon,
  FlaskConicalIcon,
  FolderIcon,
  GlobeIcon,
  GraduationCapIcon,
  HeartIcon,
  HistoryIcon,
  LanguagesIcon,
  LeafIcon,
  LibraryIcon,
  MusicIcon,
  PaletteIcon,
  ScaleIcon,
  SchoolIcon,
  ScrollIcon,
  StethoscopeIcon,
  TerminalIcon,
  TextIcon,
  TrophyIcon,
} from "lucide-react";

export const TOPIC_ICON_OPTIONS = [
  { name: "folder", icon: FolderIcon },
  { name: "book", icon: BookIcon },
  { name: "bookopen", icon: BookOpenIcon },
  { name: "brain", icon: BrainIcon },
  { name: "graduationcap", icon: GraduationCapIcon },
  { name: "school", icon: SchoolIcon },
  { name: "library", icon: LibraryIcon },
  { name: "text", icon: TextIcon },
  { name: "music", icon: MusicIcon },
  { name: "code", icon: CodeIcon },
  { name: "calculator", icon: CalculatorIcon },
  { name: "globe", icon: GlobeIcon },
  { name: "languages", icon: LanguagesIcon },
  { name: "palette", icon: PaletteIcon },
  { name: "camera", icon: CameraIcon },
  { name: "film", icon: FilmIcon },
  { name: "history", icon: HistoryIcon },
  { name: "flaskconical", icon: FlaskConicalIcon },
  { name: "dna", icon: DnaIcon },
  { name: "heart", icon: HeartIcon },
  { name: "stethoscope", icon: StethoscopeIcon },
  { name: "trophy", icon: TrophyIcon },
  { name: "dumbbell", icon: DumbbellIcon },
  { name: "binary", icon: BinaryIcon },
  { name: "database", icon: DatabaseIcon },
  { name: "briefcase", icon: BriefcaseIcon },
  { name: "terminal", icon: TerminalIcon },
  { name: "coffee", icon: CoffeeIcon },
  { name: "leaf", icon: LeafIcon },
  { name: "scale", icon: ScaleIcon },
  { name: "scroll", icon: ScrollIcon },
  { name: "atom", icon: AtomIcon },
] as const;

export const TOPIC_COLOR_OPTIONS = [
  {
    name: "neutral",
    icon: "bg-neutral-100 text-neutral-600 dark:bg-neutral-800 dark:text-neutral-300",
    bg: "bg-neutral-100 dark:bg-neutral-800",
    bg600: "bg-neutral-600",
    text: "text-neutral-600 dark:text-neutral-300",
  },
  {
    name: "red",
    icon: "bg-red-100 text-red-600 dark:bg-red-950 dark:text-red-300",
    bg: "bg-red-100 dark:bg-red-950",
    bg600: "bg-red-600",
    text: "text-red-600 dark:text-red-300",
  },
  {
    name: "orange",
    icon: "bg-orange-100 text-orange-600 dark:bg-orange-950 dark:text-orange-300",
    bg: "bg-orange-100 dark:bg-orange-950",
    bg600: "bg-orange-600",
    text: "text-orange-600 dark:text-orange-300",
  },
  {
    name: "amber",
    icon: "bg-amber-100 text-amber-600 dark:bg-amber-950 dark:text-amber-300",
    bg: "bg-amber-100 dark:bg-amber-950",
    bg600: "bg-amber-600",
    text: "text-amber-600 dark:text-amber-300",
  },
  {
    name: "yellow",
    icon: "bg-yellow-100 text-yellow-600 dark:bg-yellow-950 dark:text-yellow-300",
    bg: "bg-yellow-100 dark:bg-yellow-950",
    bg600: "bg-yellow-600",
    text: "text-yellow-600 dark:text-yellow-300",
  },
  {
    name: "lime",
    icon: "bg-lime-100 text-lime-600 dark:bg-lime-950 dark:text-lime-300",
    bg: "bg-lime-100 dark:bg-lime-950",
    bg600: "bg-lime-600",
    text: "text-lime-600 dark:text-lime-300",
  },
  {
    name: "green",
    icon: "bg-green-100 text-green-600 dark:bg-green-950 dark:text-green-300",
    bg: "bg-green-100 dark:bg-green-950",
    bg600: "bg-green-600",
    text: "text-green-600 dark:text-green-300",
  },
  {
    name: "emerald",
    icon: "bg-emerald-100 text-emerald-600 dark:bg-emerald-950 dark:text-emerald-300",
    bg: "bg-emerald-100 dark:bg-emerald-950",
    bg600: "bg-emerald-600",
    text: "text-emerald-600 dark:text-emerald-300",
  },
  {
    name: "teal",
    icon: "bg-teal-100 text-teal-600 dark:bg-teal-950 dark:text-teal-300",
    bg: "bg-teal-100 dark:bg-teal-950",
    bg600: "bg-teal-600",
    text: "text-teal-600 dark:text-teal-300",
  },
  {
    name: "cyan",
    icon: "bg-cyan-100 text-cyan-600 dark:bg-cyan-950 dark:text-cyan-300",
    bg: "bg-cyan-100 dark:bg-cyan-950",
    bg600: "bg-cyan-600",
    text: "text-cyan-600 dark:text-cyan-300",
  },
  {
    name: "sky",
    icon: "bg-sky-100 text-sky-600 dark:bg-sky-950 dark:text-sky-300",
    bg: "bg-sky-100 dark:bg-sky-950",
    bg600: "bg-sky-600",
    text: "text-sky-600 dark:text-sky-300",
  },
  {
    name: "blue",
    icon: "bg-blue-100 text-blue-600 dark:bg-blue-950 dark:text-blue-300",
    bg: "bg-blue-100 dark:bg-blue-950",
    bg600: "bg-blue-600",
    text: "text-blue-600 dark:text-blue-300",
  },
  {
    name: "indigo",
    icon: "bg-indigo-100 text-indigo-600 dark:bg-indigo-950 dark:text-indigo-300",
    bg: "bg-indigo-100 dark:bg-indigo-950",
    bg600: "bg-indigo-600",
    text: "text-indigo-600 dark:text-indigo-300",
  },
  {
    name: "violet",
    icon: "bg-violet-100 text-violet-600 dark:bg-violet-950 dark:text-violet-300",
    bg: "bg-violet-100 dark:bg-violet-950",
    bg600: "bg-violet-600",
    text: "text-violet-600 dark:text-violet-300",
  },
  {
    name: "purple",
    icon: "bg-purple-100 text-purple-600 dark:bg-purple-950 dark:text-purple-300",
    bg: "bg-purple-100 dark:bg-purple-950",
    bg600: "bg-purple-600",
    text: "text-purple-600 dark:text-purple-300",
  },
  {
    name: "fuchsia",
    icon: "bg-fuchsia-100 text-fuchsia-600 dark:bg-fuchsia-950 dark:text-fuchsia-300",
    bg: "bg-fuchsia-100 dark:bg-fuchsia-950",
    bg600: "bg-fuchsia-600",
    text: "text-fuchsia-600 dark:text-fuchsia-300",
  },
  {
    name: "pink",
    icon: "bg-pink-100 text-pink-600 dark:bg-pink-950 dark:text-pink-300",
    bg: "bg-pink-100 dark:bg-pink-950",
    bg600: "bg-pink-600",
    text: "text-pink-600 dark:text-pink-300",
  },
  {
    name: "rose",
    icon: "bg-rose-100 text-rose-600 dark:bg-rose-950 dark:text-rose-300",
    bg: "bg-rose-100 dark:bg-rose-950",
    bg600: "bg-rose-600",
    text: "text-rose-600 dark:text-rose-300",
  },
] as const;
